_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 69aefa02-b1be-48b6-b661-f800a03b9bc8
name: 'Innoraft Employee Management Portal'
mail: portaladmin@employconnect.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
